In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/lukeyang01/nn-from-scratch/main/week2_data.csv')

inputs = np.array(df.iloc[:, 0:2])
labels = np.array(df.iloc[:, 2])

In [ ]:
def sigmoid(x: int) -> float:
  """Sigmoid activation function."""
  return 1 / (1 + np.exp(-x))

def sigmoid_back(x: int) -> float:
  """Derivative of sigmoid for backward calculation."""
  fwd = sigmoid(x)
  return fwd * (1-fwd)

In [ ]:
class MLP:
  """A Neural Network Class to Perform Basic Feedforward algorithm and training"""
  def __init__(self, sizes: list):
    """Initialize a numpy array or a list of weights an array or list of weights depending on sizes"""
    self.sizes = sizes
    self.num_layers = len(sizes)
    self.weights = []
    self.biases = []

    self.__init_params()
    return

  def __init_params(self):
    # iteration over network layers
      for i in range(1, self.num_layers):
          # X inputs -> Y Ouputs
          in_size = self.sizes[i-1]
          out_size = self.sizes[i]

          # weights.shape = (Y, X), biases.shape = (Y, 1)
          # e.g. 2 -> 3: weights is (2,3), biases is (1,3)
          self.weights.append(np.random.randn(in_size, out_size) * 0.1)
          self.biases.append(np.random.randn(1, out_size) * 0.1)
          # print(self.weights[-1].shape, self.biases[-1].shape)

  def forward(self, x: np.ndarray):
    """
      Perform feedforward algorithm on input vector for all layers

      Input:    x: np.ndarray with shape (1, self.sizes[0])

      Returns:  y: np.ndarray with shape (1, self.sizes[-1])
    """
    # Reshape the input vector to match specs this way inputs can be passed in any shape.
    x = x.reshape(1, self.sizes[0])

    # TODO: For each layer in network, perform feed forward algorithm
    # Hint: Use np.matmul instead of np.dot here (1x2 input) * (2x3 weights) -> (1x3 output)
    # Hint: The zip function may be helpful but is non nessecary

    # taking weighted sum
    # not taking final layer because output layer
    for i in range(self.num_layers - 1):
      x = np.matmul(x, self.weights[i]) + self.biases[i]  #add bias value to all values in weighted sum
      if(i < self.num_layers - 2):
        sigmoid(x)

    return x

  def backward(self, x, y):
    """Perform backpropagation using the input and expected output to get weight and vector deltas"""
    return False

  def train(self, X_train, y_train, epochs=1, lr=0.01, batch_size=1, verbose=True):
    """Using forward and backward functions, fit the model on an entire training step using gradient descent algorithm."""
    return False

In [ ]:
def main():
  nn = MLP([2, 3, 2])
  for x in inputs:
    val = nn.forward(x)
    print(val)

In [ ]:
main()

[[-0.10889629  0.01988998]]
[[-0.10768665  0.03094609]]
[[-0.08582388  0.00186662]]
[[-0.08580991 -0.00774502]]
[[-0.11207798  0.03687545]]
[[-0.08726455  0.00197428]]
[[-0.09397937  0.01790574]]
[[-0.09127501  0.01719781]]
[[-0.11138122  0.05782356]]
[[-0.10632265  0.01330984]]
[[-0.1120985   0.02364944]]
[[-0.10323067  0.03380017]]
[[-0.10169593  0.02662525]]
[[-0.10840692  0.0332394 ]]
[[-0.08547397 -0.00481611]]
[[-0.1200445   0.05425127]]
[[-0.113835    0.02635484]]
[[-0.11509281  0.03229072]]
[[-0.11103557  0.02262086]]
[[-0.11389651  0.04071255]]
[[-0.10070053  0.02619377]]
[[-0.1043789   0.03097297]]
[[-0.0954877   0.00217783]]
[[-0.09133477 -0.00353342]]
[[-0.11404006  0.05178668]]
[[-0.10933249  0.02435373]]
[[-0.09888654  0.02949547]]
[[-0.1128876   0.04990975]]
[[-0.10077374  0.03937019]]
[[-0.10555694  0.02492213]]
[[-0.10478113  0.03662906]]
[[-0.09383393  0.00331081]]
[[-0.11503578  0.04362004]]
[[-0.0976848   0.02254901]]
[[-0.10597159  0.03156701]]
[[-0.08690003  0.008